### PR TITLE
Build for and test Python 3.10.

### LINKED ISSUE #17: Python 3.1.0 Wheels
Hi Kristof! 

Thanks so much for this library and for accepting my PRs a few months back. I finally integrated it into https://github.com/seung-lab/igneous to create multi-resolution meshes. No rush, but would it be possible to get Python 3.10 wheels on PyPI? py310 is getting more popular so it's probably inevitable that someone needs it.

Thanks so much!
Will

### PR DESCRIPTION
**Pull request by bwoodsend**
Closes #17.

### CODE REVIEW

**Comment by friggog** [comment]
Anything stopping this from being completed? Would be great to have 3.10 support!

**Comment by bwoodsend** [comment]
@Kramer84

**Comment by bwoodsend** [comment]
Uh oh. The man with the PyPI permissions has gone AWOL. I do have permission to hit the merge button in his absence but then I won't be able to upload the wheels to PyPI without Kristof...

**Comment by friggog** [comment]
Seems like the build action also needs to be manually triggered?

**Comment by bwoodsend** [comment]
Yeah, we need to increment the version, trigger that workflow then `twine upload` the wheels it produces. @Kramer84 Can you do that? You're the only one who has permission to do the `twine upload`.

**Comment by Kramer84** [comment]
Version got updated to 0.1.2, build triggered and as soon as it's finished it gets pushed in PyPI!
Sorry for the reaction time, I kinda saw the notifications too late

**Pull request merged**
