### PR TITLE
Build wheels for all platforms on Github actions

### PR DESCRIPTION
**Pull request by bwoodsend**
As promised, here's something to build all the wheels we need to go on PyPI. An example of it in action can be found [here](https://github.com/bwoodsend/pyFMR-Fast-quadric-Mesh-Reduction/actions/runs/1119777055). The wheels it built are downloadable at the bottom of that page.

### CODE REVIEW

**Comment by bwoodsend** [comment]
@Kramer84 Are you still there? With this merged we can build the wheels and finish off #3.

**Comment by Kramer84** [comment]
@bwoodsend Yes, I had to take some time last month to work on other projects, plus I tried to put it on PyPI but had the unsupported platform tag 'linux_x86_64' error.

I am hoping to solve the issue with manylinux in the coming days.

**Comment by william-silversmith** [comment]
Any luck with the manylinux issue? I was able to build a set of manylinux2014 wheels locally using docker without issue for x86_64 cpython3.6 thru 3.9 inclusive. I also have an example for packaging wheels using GHA: https://github.com/seung-lab/connected-components-3d/blob/master/.github/workflows/build_wheel.yml I usually download them and upload them manually using twine to have more control, but you can set it up to deploy automatically as well.

### Dockerfile

```dockerfile
FROM quay.io/pypa/manylinux2014_x86_64 

ADD . /build

WORKDIR "/build"

ENV CXX "g++"

RUN rm -rf *.so build __pycache__ dist 

RUN /opt/python/cp36-cp36m/bin/pip3.6 install pip --upgrade
RUN /opt/python/cp36-cp36m/bin/pip3.6 install -e .
RUN /opt/python/cp36-cp36m/bin/pip3.6 install -r tests/requirements.txt
RUN /opt/python/cp36-cp36m/bin/python3.6 -m pytest -v -x tests

RUN /opt/python/cp37-cp37m/bin/pip3.7 install pip --upgrade
RUN /opt/python/cp37-cp37m/bin/pip3.7 install -e .
RUN /opt/python/cp37-cp37m/bin/pip3.7 install -r tests/requirements.txt
RUN /opt/python/cp37-cp37m/bin/python3.7 -m pytest -v -x tests

RUN /opt/python/cp38-cp38/bin/pip3.8 install pip --upgrade
RUN /opt/python/cp38-cp38/bin/pip3.8 install -e .
RUN /opt/python/cp38-cp38/bin/pip3.8 install -r tests/requirements.txt
RUN /opt/python/cp38-cp38/bin/python3.8 -m pytest -v -x tests

RUN /opt/python/cp39-cp39/bin/pip3.9 install pip --upgrade
RUN /opt/python/cp39-cp39/bin/pip3.9 install -e .
RUN /opt/python/cp39-cp39/bin/pip3.9 install -r tests/requirements.txt
RUN /opt/python/cp39-cp39/bin/python3.9 -m pytest -v tests

RUN /opt/python/cp36-cp36m/bin/python3.6 setup.py bdist_wheel
RUN /opt/python/cp37-cp37m/bin/python3.7 setup.py bdist_wheel
RUN /opt/python/cp38-cp38/bin/python3.8 setup.py bdist_wheel
RUN /opt/python/cp39-cp39/bin/python3.9 setup.py bdist_wheel

RUN for whl in `ls dist/*.whl`; do auditwheel repair $whl --plat manylinux2014_x86_64; done
```

### Runner Bash Script

```bash
#!/bin/bash
container_name=pyfqmr
echo "Building kramer84/$container_name"
# docker build . -f manylinux1.Dockerfile --tag "kramer84/$container_name:manylinux1"
# docker build . -f manylinux2010.Dockerfile --tag "kramer84/$container_name:manylinux2010"
docker build . -f manylinux2014.Dockerfile --tag "kramer84/$container_name:manylinux2014"
# docker run -v $PWD/dist:/output "kramer84/$container_name:manylinux1" /bin/bash -c "cp -r wheelhouse/* /output"
# docker run -v $PWD/dist:/output "kramer84/$container_name:manylinux2010" /bin/bash -c "cp -r wheelhouse/* /output"
docker run -v $PWD/dist:/output "kramer84/$container_name:manylinux2014" /bin/bash -c "cp -r wheelhouse/* /output"
```

Thanks again for entertaining my requests and PRs!

**Comment by bwoodsend** [comment]
Whenever we want wheels built, it's just a case of pressing the **Run Workflow** button [on the workflow's page](https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction/actions/workflows/build-wheels.yml) (@william-silversmith you won't be able to see it because it requires push access but if you merge push this repo's master branch into your fork then you should be able to see it in the actions tab for your fork). [Here's](https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction/suites/4462141106/artifacts/118576743) an example batch. Because the Linux wheels are tagged `manylinux` instead of just `linux`, PyPI will accept them.

**Comment by william-silversmith** [comment]
Ah okay, sorry. I saw the wheels were not uploaded on PyPI and thought that this might still be an issue. Thanks for clarifying!

**Comment by bwoodsend** [comment]
Yeah, @Kramer84 anything holding you back from uploading those wheels?

**Comment by Kramer84** [comment]
Nothing more then my non-existent experience concerning manywheels and deploying packages on PyPi. Perhaps the README.md should be rewritten in restructured text, cause during my testing I got this error :

```console
twine upload --verbose  pyfqmr-1.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
Uploading distributions to https://upload.pypi.org/legacy/
  pyfqmr-1.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (729.1 KB)
Enter your username: kramer84
Enter your password: 
username: kramer84
password: <hidden>
Uploading pyfqmr-1.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
100%|████████████████████████████████████████████████████████████| 735k/735k [00:42<00:00, 17.7kB/s]
Content received from server:
<html>
 <head>
  <title>400 The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.</title>
 </head>
 <body>
  <h1>400 The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.


 </body>
</html>
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
``` 

I am consulting one of my colleagues who has a experience in deploying packages on PyPI for assisting me in this step.   

Do you have experience in preparing the workflow in such a way that during each new push automatically updates the PyPi package?

**Comment by william-silversmith** [comment]
Was this the newest version? I had that problem in my repo and solved it by adding `long_description_content_type='text/markdown',` to the setup.py file. I added that in the version that's on master now.

**Comment by Kramer84** [comment]
I am not so sure, I made the tests with the first build artifact made by @bwoodsend , but as it did not work I switched the README into rst format, which I hope, will not break anything! (and at the same time removed your new line, as it's not needed with RST)

I'm testing now on the dev branch by with an empty README.rst file, as I still have the same error message even when switching to RST

**Comment by bwoodsend** [comment]
That `long_description_content_type='text/markdown',` line would have done it. The only reason it didn't is because that line wasn't yet in the master branch when I triggered that build. But I suppose there's no harm done in switching to rST.

**Comment by william-silversmith** [comment]
Just wanted to check in. Seems `pyfqmr` is no longer on PyPI. If some help is needed, I'm happy to help here, via email, or zoom if needed. Should be an easy thing to fix.

**Comment by Kramer84** [comment]
Thank you for the offer @william-silversmith, but I finally managed to get it on [PyPI.](https://pypi.org/project/pyfqmr/0.1.0/) It can now be installed with pip! And we can go on and include the new dependencies and optimizations.

**Comment by william-silversmith** [comment]
Fantastic! Thank you for your hard work!

**Pull request merged**
